@Host = http://localhost:5000

###
GET {{Host}}/api/members
###
# GET {{Host}}/api/members/{{memberId}}
###

###
# POST a new member
POST {{Host}}/api/members/member-register
Content-Type: application/json

{
  "full_name": "Professional Dev",
  "phone_number": "000111222",
  "gender": "Male",
  "emergency_contact": "999888"
}
